
from USRR import USRR




if __name__ == '__main__':
    dna = 'AAAATAGTAGTAGTAGTAGTAGTATGATATGATATGATAGGACCCCAGGGACGCCATTTTACCCCCAGGGAGCGCAGGCGCGCGCGCAGCGCAGCTACTATACTGCTGCGACTGCCTTCTCTACTACTACTCGACATCTAC'
    #dna = "TAGTAGTAGGGG"
    handler = USRR(dna)
    SRR_list = handler.find_all_srr()
    print(SRR_list)

